### PR TITLE
Convert line endings from CRLF to LF.

### PR DESCRIPTION
**Pull request by johnjohndoe**
- This commit does not introduce any code change.

### CODE REVIEW

**Comment by pnc** [comment]
This is a Windows `.bat`, so [CRLF line endings are correct](http://serverfault.com/a/429598/201573).

**Comment by johnjohndoe** [comment]
I disagree.  The Git repository should only contain Unix style line endings (line feed: `LF`) by convention. The file I converted had Windows style line endings (carriage return line feed: `CRLF`). This causes a **full file diff** everytime someone **checks out your repository** or **changes a branch** on a Unix machine (Linux, MacOSX).
In order to support Windows machines Git can be configured to **automatically convert** the line endings of every file at checkout time. When the file is committed the reverse conversion is applied. The [Git config documentation](http://git-scm.com/docs/git-config) explains how this can be achieved.

**Comment by pnc** [comment]
@johnjohndoe I agree in spirit that Git repositories should normally only contain LF endings, but I consider `gradlew.bat` an exception for two reasons:
1. `gradlew.bat` needs to run properly on a freshly-cloned copy of the repository on Windows machines, without special Git configuration for line endings
2. `gradlew.bat` should never be edited, since it's generated

It sounds like you have a local configuration issue with Git or your development tools. I'm able to clone and modify this repository on OS X without seeing errant changes on `gradlew.bat`. Perhaps something is rewriting these files without your consent?

**Comment by pnc** [comment]
Perhaps the local changes you're seeing can be resolved with the `-crlf` option in a `.gitattributes` file—if so, I'd be happy to merge that as a PR!

**Comment by johnjohndoe** [comment]
Nowadays Git is capable to handle checkouts on different operating systems automatically correctly with the default configuration. Therefore, Windows users are fine.
The `gradlew.bat` isn't technically speaking generated but copied from the system Gradle version such as via the `gradle wrapper` command. I do not rate the conversion of line endings on this file as an no-go edit. I should have been done right in the first place by the Gradle authors.

**Comment by johnjohndoe** [comment]
For your reference:

> Formatting and whitespace issues are some of the more frustrating and subtle problems that many developers encounter when collaborating, especially cross-platform. It’s very easy for patches or other collaborated work to introduce subtle whitespace changes because editors silently introduce them, and if your files ever touch a Windows system, their line endings might be replaced. Git has a few configuration options to help with these issues.
> 
> `core.autocrlf`
> 
> If you’re programming on Windows and working with people who are not (or vice-versa), you’ll probably run into line-ending issues at some point. This is because Windows uses both a carriage-return character and a linefeed character for newlines in its files, whereas Mac and Linux systems use only the linefeed character. This is a subtle but incredibly annoying fact of cross-platform work; many editors on Windows silently replace existing LF-style line endings with CRLF, or insert both line-ending characters when the user hits the enter key.
> 
> Git can handle this by auto-converting CRLF line endings into LF when you add a file to the index, and vice versa when it checks out code onto your filesystem ...

Source: [Git documentation - Configuration - Formatting-and-Whitespace](https://git-scm.com/book/en/v2/Customizing-Git-Git-Configuration#Formatting-and-Whitespace)

**Pull request closed without merging**
