### PR TITLE
 	Use 'com-phillipcalvin-iconbutton' as artifact id.

### PR DESCRIPTION
**Pull request by msdx**

### CODE REVIEW

**Comment by pnc** [comment]
IIRC, Android's stock `Button` supports aligning the text but not the icon (`center="text"`)—I wrote this class specifically to support the `both` case, since `text` was already covered by the normal functionality. Is there something that the built-in class doesn't support that necessitates using an IconButton for this?

Also, there are two things going on this PR: one is the the artifact ID change and one is the addition of the `center` attribute. Can you split these into two pull requests? Thanks!

**Comment by msdx** [comment]
I don't know how to split these into two pull requests, but I know that `git cherry-pick` can merge one commit into the branch.

**Comment by msdx** [comment]
I has removed the commits after `e5d8bed` at master.

**Comment by pnc** [comment]
@msdx Cool, thank you!

**Comment by pnc** [comment]
@msdx Do I need to make a bintray account and upload this in order for the instructions in the README to work?

**Comment by msdx** [comment]
@pnc You don't need to do, because I had upload the files with my bintray account. 
But if you have a bintray or maven(www.maven.org) account, you can upload this, then the dependency declaration will be like this:
` compile 'your.group:iconbutton:1.0.1@aar'`
And I also suggest you to do so. After all it is your original project. :)

**Pull request merged**
